env: stage
components:
  - name: ds-scheduling-reservation-hostedzone
    provider:
      name: cdk
      config:
        account: ${ds-scheduling-stage:aws}
        region: us-west-2
        constructPackage: '@daysmart/cdk-multi-accont-dns'
        constructName: DelegatedHostedZone
    inputs:
      zoneName: stage.reservation.daysmart.com
  - name: ds-scheduling-dns-ns-records
    provider:
      name: cdk
      config:
        account: ${og-legacy-main:aws}
        region: us-east-1
        constructPackage: '@daysmart/cdk-multi-accont-dns'
        constructName: DelegatedNSRecord
    inputs:
      hostedZoneDomain: daysmart.com
      delegatedDomainName: stage.reservation.daysmart.com
      nameServers: ${stage:ds-scheduling-reservation-hostedzone:NameServers}
