env: stage
components:
  - name: ds-scheduling-reservation-cert
    provider:
      name: cdk
      config:
        constructPackage: '@daysmart/cdk-multi-accont-dns'
        constructName: HostedZoneCertificate
        account: ${ds-scheduling-stage:aws}
        region: 'us-west-2'
    inputs:
      domainName: stage.reservation.daysmart.com
