env: dev
components:
  - name: ds-scheduling-reservation-hostedzone
    provider:
      name: cdk
      config:
#        account: "631541896113"
        account: ${ds-scheduling-dev:aws}
        region: us-west-2
        constructPackage: '@daysmart/cdk-multi-accont-dns'
        constructName: DelegatedHostedZone
    inputs:
      zoneName: dev.reservation.daysmart.com
  - name: ds-scheduling-dns-ns-records
    provider:
      name: cdk
      config:
        account: ${og-legacy-main:aws}
        region: us-east-1
        constructPackage: '@daysmart/cdk-multi-accont-dns'
        constructName: DelegatedNSRecord
    inputs:
      hostedZoneDomain: daysmart.com
      delegatedDomainName: dev.reservation.daysmart.com
      nameServers: ${dev:ds-scheduling-reservation-hostedzone:NameServers}
