env: prod
components:
  - name: ds-scheduling-reservation-cert
    provider:
      name: cdk
      config:
        constructPackage: '@daysmart/cdk-multi-accont-dns'
        constructName: HostedZoneCertificate
        account: ${ds-scheduling-prod:aws}
        region: 'us-west-2'
    inputs:
      domainName: reservation.daysmart.com
